sudo: false

language: node_js

node_js: 8

cache:
  yarn: true
  directories:
    - $HOME/.cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - stage: test
      script: yarn test --maxWorkers=2
    - stage: test
      node_js: 10
      script: yarn test --maxWorkers=2
    - stage: code coverage
      script:
        - yarn test --maxWorkers=2 --coverage
        - bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info
