sudo: false

language: node_js

node_js:
  - 7
  - 6
  - 4

cache:
  directories:
    - $HOME/.cache

before_install:
  # Ensure npm 4 on Node 4
  - '[ "${TRAVIS_NODE_VERSION}" != 4 ] || npm install -g npm@latest'
